name: "Repository Dependents Image Action"
author: "Gourav Khunger"

description: "Generates a list of the dependents of a repository to be later rendered in the README."

inputs:
  repo:
    description: "Owner and name of the repository (example: owner/repo)"
    required: true
  upload-artifacts:
    description: "Whether to upload the outputs as artifacts (true/false)"
    required: false
    default: "false"

outputs:
  dependents:
    description: "List of dependents of the repository."

runs:
  using: 'node20'
  main: 'action/dist/index.js'
