name: "Dependents Info Action"
author: "Gourav Khunger"

description: "Generates a list of the dependents of a repository to be later rendered in the README."

branding:
  icon: "users"
  color: "white"

inputs:
  unique-owners:
    description: "Whether to disable unique users (true/false)"
    required: false
    default: true
    type: boolean
  upload-artifacts:
    description: "Whether to upload the outputs as artifacts (true/false)"
    required: false
    default: false
    type: boolean

outputs:
  dependents:
    description: "List of dependents of the repository."

runs:
  using: 'node20'
  main: 'action/dist/index.js'
