name: "Dependents Info Action"
author: "Gourav Khunger"

description: "Generates a list of the dependents of a repository to be later rendered in the README."

branding:
  icon: "users"
  color: "white"

inputs:
  package-id:
    description: "GitHub package ID to process (if the repository publishes multiple)"
    required: false
    type: string
  max-pages:
    description: "Maximum number of pages to process (default: 50, max: 100)"
    required: false
    default: 50
    type: integer
  unique-owners:
    description: "Whether to disable unique users (true/false)"
    required: false
    default: true
    type: boolean
  exclude-owner:
    description: "Whether to exclude repositories from the same owner that depend on this repository (true/false)"
    required: false
    default: true
    type: boolean
  upload-artifacts:
    description: "Whether to upload the outputs as artifacts (true/false)"
    required: false
    default: true
    type: boolean
  force-run:
    description: "Force submit dependents data to the API. Only required for forked repositories (true/false)"
    required: false
    default: false
    type: boolean

outputs:
  dependents:
    description: "List of dependents of the repository."

runs:
  using: 'node20'
  main: 'action/dist/index.js'
